export const GROUPS = [
  { id: "all", label: "All" },
  { id: "limitations", label: "FCOM Limits" },
  { id: "memory", label: "Memory Items" },
  { id: "braking", label: "Loss of Braking" },
  { id: "descent", label: "Emer Descent" },
  { id: "uas", label: "Unreliable Airspeed" },
  { id: "stall", label: "Stall at Liftoff" },
  { id: "evac", label: "Evacuation" },
];

function stepLine(step) {
  return [step.item, step.action].filter(Boolean).join(" ");
}

function withSequence(item) {
  return {
    ...item,
    kind: "sequence",
    ordered: true,
    answer: item.steps.map(stepLine).join(", "),
  };
}

export const ITEMS = [
  {
    id: "max-alt",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Maximum Operating Altitude",
    answer: "43,100 feet pressure altitude",
    keys: ["43100"],
  },
  {
    id: "tw-to-ldg",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Maximum Takeoff and Landing Tailwind Component",
    answer: "15 knots, or as permitted by the Company Pages",
    keys: ["15"],
  },
  {
    id: "xw-to",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Crosswind limit for takeoff",
    answer: "35 knots (including gusts)",
    keys: ["35"],
  },
  {
    id: "xw-ldg",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Crosswind limit for landing",
    answer: "40 knots (including gusts)",
    keys: ["40"],
  },
  {
    id: "ap-to",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Autopilot engagement on takeoff",
    answer: "Must not be engaged until at least 5 seconds after lift-off",
    keys: ["5"],
  },
  {
    id: "ap-ga",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Autopilot after a manual go around",
    answer: "Must not be engaged below 100 feet AGL",
    keys: ["100"],
  },
  {
    id: "autoland-hw",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Autoland headwind",
    answer: "40 knots",
    keys: ["40"],
  },
  {
    id: "autoland-tw",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Autoland tailwind",
    answer: "15 knots",
    keys: ["15"],
  },
  {
    id: "autoland-xw",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Autoland crosswind",
    answer: "30 knots",
    keys: ["30"],
  },
  {
    id: "flaps-alt",
    kind: "value",
    group: "limitations",
    section: "FCOM Limitations",
    prompt: "Flaps extension altitude limit",
    answer: "Do not extend flaps above 20,000 feet",
    keys: ["20000"],
  },
  withSequence({
    id: "braking",
    group: "braking",
    section: "Memory Items",
    prompt: "Loss of Braking",
    context: "If no braking, then if still no braking",
    steps: [
      { item: "REV", action: "MAX" },
      { item: "BRAKE PEDALS", action: "RELEASE" },
      { item: "A-SKID OFF", action: "ORDER" },
      { item: "A-SKID", action: "OFF" },
      { item: "BRAKE PEDALS", action: "PRESS" },
      { item: "PARK BRK", action: "USE" },
    ],
    keys: [
      "REV MAX",
      "BRAKE PEDALS RELEASE",
      "ASKID OFF ORDER",
      "ASKID OFF",
      "BRAKE PEDALS PRESS",
      "PARK BRK USE",
    ],
  }),
  withSequence({
    id: "descent",
    group: "descent",
    section: "Memory Items",
    prompt: "Emer Descent",
    context: "If the cabin pressure altitude is above 10,000 ft. Initiate with AUTO EMER DESCENT or selected guidance via the AFS CP.",
    steps: [
      { item: "CREW OXY MASKS", action: "USE" },
      { item: "SIGNS", action: "ON" },
      { item: "EMER DESCENT", action: "INITIATE" },
      { item: "ALL THR LEVERS", action: "IDLE if A/THR not active" },
      { item: "SPEED BRAKES LEVER", action: "FULL if A/THR not active" },
    ],
    keys: [
      "CREW OXY MASKS USE",
      "SIGNS ON",
      "EMER DESCENT INITIATE",
      "ALL THR LEVERS IDLE",
      "SPEED BRAKES LEVER FULL",
    ],
  }),
  withSequence({
    id: "uas",
    group: "uas",
    section: "Memory Items",
    prompt: "Unreliable Air Speed Indication",
    context: "If the safe conduct of the flight is impacted",
    steps: [
      { item: "A/P", action: "OFF" },
      { item: "A/THR", action: "OFF" },
      { item: "FD", action: "OFF" },
      { item: "PITCH/THRUST", action: "Below THR RED ALT 12.5°/TOGA" },
      {
        item: "PITCH/THRUST",
        action: "Above THR RED ALT and Below FL 100 10°/CLB",
      },
      {
        item: "PITCH/THRUST",
        action: "Above THR RED ALT and Above FL 100 5°/CLB",
      },
      { item: "FLAPS", action: "MAINTAIN CURRENT CONF if CONF 0(1)(2)(3)" },
      { item: "FLAPS", action: "SELECT CONF 3 AND MAINTAIN if CONF FULL" },
      { item: "SPEED BRAKES", action: "CHECK RETRACTED" },
      { item: "L/G", action: "UP" },
    ],
    keys: [
      "AP OFF",
      "ATHR OFF",
      "FD OFF",
      "12.5 TOGA",
      "10 CLB",
      "5 CLB",
      "MAINTAIN CURRENT CONF",
      "CONF 3",
      "CHECK RETRACTED",
      "LG UP",
    ],
  }),
  withSequence({
    id: "stall",
    group: "stall",
    section: "Memory Items",
    prompt: "Stall Warning at Liftoff",
    context: "If stall warnings trigger at liftoff, apply immediately, at the same time",
    steps: [
      { item: "THRUST", action: "TOGA" },
      { item: "PITCH ATTITUDE", action: "12.5°" },
      { item: "BANK", action: "WINGS LEVEL" },
    ],
    keys: ["THRUST TOGA", "PITCH ATTITUDE 12.5", "BANK WINGS LEVEL"],
  }),
  withSequence({
    id: "evac",
    group: "evac",
    section: "1.3 Emergency Evacuation Flow/Philosophy",
    prompt: "Emergency Evacuation Flow/Philosophy",
    ask: "What is the emergency evacuation flow/philosophy?",
    context:
      "Memorize this flow if the checklist cannot be read due to smoke/fire, darkness, injury, or incapacitation.",
    steps: [
      { item: "STOP", action: "" },
      { item: "CONFIGURE", action: "" },
      { item: "SHUTDOWN", action: "" },
      { item: "EVACUATE", action: "" },
    ],
    keys: ["STOP", "CONFIGURE", "SHUTDOWN", "EVACUATE"],
  }),
];

export const ITEM_BY_ID = Object.fromEntries(ITEMS.map((item) => [item.id, item]));
